/*******************************************/
/*		Author	: Pola Magdy			   */
/*		Version	: V01					   */
/*		Date	: 6/11/2023			 	   */
/*     Description: DIO_Cfg.c		       */
/*******************************************/

#include "StdTypes.h"
#include "DIO_Interface.h"

const DIO_PinStatus_type DIO_PinsStatusArr[TOTAL_PINS]={
	
	OUTPUT10KHZ_PUSHPALL,			//PINA0
	OUTPUT10KHZ_PUSHPALL,			//PINA1
	OUTPUT10KHZ_PUSHPALL,			//PINA2
	OUTPUT10KHZ_PUSHPALL,			//PINA3
	OUTPUT10KHZ_PUSHPALL,			//PINA4
	OUTPUT10KHZ_PUSHPALL,			//PINA5
	OUTPUT10KHZ_PUSHPALL,			//PINA6
	OUTPUT10KHZ_PUSHPALL,			//PINA7
	OUTPUT10KHZ_PUSHPALL,			//PINA8
	OUTPUT10KHZ_PUSHPALL,			//PINA9
	OUTPUT50KHZ_PUSHPALL,			//PINA10
	OUTPUT50KHZ_PUSHPALL,			//PINA11
	OUTPUT50KHZ_PUSHPALL,			//PINA12
	OUTPUT50KHZ_PUSHPALL,			//PINA13
	OUTPUT10KHZ_PUSHPALL,			//PINA14
	OUTPUT10KHZ_PUSHPALL,			//PINA15
	OUTPUT10KHZ_PUSHPALL,			//PINB0
	OUTPUT10KHZ_PUSHPALL,			//PINB1
	OUTPUT10KHZ_PUSHPALL,			//PINB2
	OUTPUT50KHZ_PUSHPALL,			//PINB3
	OUTPUT50KHZ_PUSHPALL,			//PINB4
	OUTPUT50KHZ_PUSHPALL,			//PINB5
	OUTPUT50KHZ_PUSHPALL,			//PINB6
	OUTPUT50KHZ_PUSHPALL,			//PINB7
	OUTPUT50KHZ_PUSHPALL,			//PINB8
	OUTPUT50KHZ_PUSHPALL,			//PINB9
	OUTPUT50KHZ_PUSHPALL,			//PINB10
	OUTPUT50KHZ_PUSHPALL,			//PINB11
	OUTPUT50KHZ_PUSHPALL,			//PINB12
	OUTPUT50KHZ_PUSHPALL,			//PINB13
	OUTPUT50KHZ_PUSHPALL,			//PINB14
	OUTPUT50KHZ_PUSHPALL,			//PINB15
	OUTPUT50KHZ_PUSHPALL,			//PINC0
	OUTPUT50KHZ_PUSHPALL,			//PINC1
	OUTPUT50KHZ_PUSHPALL,			//PINC2
	OUTPUT50KHZ_PUSHPALL,			//PINC3
	OUTPUT50KHZ_PUSHPALL,			//PINC4
	OUTPUT50KHZ_PUSHPALL,			//PINC5
	OUTPUT50KHZ_PUSHPALL,			//PINC6
	OUTPUT50KHZ_PUSHPALL,			//PINC7
	OUTPUT50KHZ_PUSHPALL,			//PINC8
	OUTPUT50KHZ_PUSHPALL,			//PINC9
	OUTPUT50KHZ_PUSHPALL,			//PINC10
	OUTPUT50KHZ_PUSHPALL,			//PINC11
	OUTPUT50KHZ_PUSHPALL,			//PINC12
	OUTPUT50KHZ_PUSHPALL,			//PINC13
	OUTPUT50KHZ_PUSHPALL,			//PINC14
	OUTPUT50KHZ_PUSHPALL,			//PINC15
};
